# Python & NumPy Foundations
### Self-learning

This notebook gets you up to speed on the Python tools. You don't need to submit this notebook. Feel free to find other learning resources. 


**How to run a cell:** click on it and press `Shift + Enter`.

## 1. Python Basics

### 1.1 Variables and Types

Python variables need no declaration — the type is inferred automatically.

In [1]:
# Example 1.1
x = 5           # int
y = 3.14        # float
name = "Alice"  # str
flag = True     # bool

print(type(x), x)
print(type(y), y)
print(type(name), name)
print(type(flag), flag)

<class 'int'> 5
<class 'float'> 3.14
<class 'str'> Alice
<class 'bool'> True


In [ ]:
# Exercise 1.1
# Define variables for the width and height of a rectangle (use floats).
# Compute and print the area and perimeter.

# YOUR CODE HERE

### 1.2 Lists

A list is an ordered, mutable sequence. Index from the front with `0, 1, 2, ...` or from the back with `-1, -2, ...`

In [ ]:
# Example 1.2
temps = [22.1, 19.5, 25.3, 18.0, 21.7]

print("First element:", temps[0])
print("Last element: ", temps[-1])
print("Slice [1:3]:  ", temps[1:3])
print("Length:       ", len(temps))

temps.append(23.4)
print("After append: ", temps)

In [ ]:
# Exercise 1.2
# Create a list of 5 integers of your choice. Then:
# (a) Print the sum by looping over the list (do not use the built-in sum()).
# (b) Replace the third element with 0 and print the modified list.

# YOUR CODE HERE

### 1.3 Control Flow

`if / elif / else` for branching; `for` to iterate over a sequence.

In [ ]:
# Example 1.3
score = 78

if score >= 90:
    print("A")
elif score >= 80:
    print("B")
else:
    print("C or below")

# for loop — accumulate a sum
total = 0
for val in [3, 1, 4, 1, 5, 9]:
    total += val
print("Sum:", total)

In [ ]:
# Exercise 1.3
# Print the numbers 1 through 20.
# For multiples of 3, print "Fizz" instead.
# For multiples of 5, print "Buzz" instead.
# For multiples of both 3 and 5, print "FizzBuzz".

# YOUR CODE HERE

### 1.4 Functions

Use `def` to define a reusable block of code. Functions take inputs (parameters) and return an output with `return`.

In [ ]:
# Example 1.4
def celsius_to_fahrenheit(c):
    return 9/5 * c + 32

print(celsius_to_fahrenheit(0))    # 32.0
print(celsius_to_fahrenheit(100))  # 212.0

# Functions can have multiple parameters and a default value
def greet(name, greeting="Hello"):
    return f"{greeting}, {name}!"

print(greet("Bob"))
print(greet("Bob", "Hi"))

In [ ]:
# Exercise 1.4
# Write a function factorial(n) that returns n! using a loop (not recursion).
# It should handle n = 0 (by convention, 0! = 1).
# Test it on n = 0, 1, 5, and 10.

# YOUR CODE HERE

### 1.5 List Comprehensions

A concise way to build a new list from an existing sequence.

In [ ]:
# Example 1.5
squares = [x**2 for x in range(6)]
print(squares)   # [0, 1, 4, 9, 16, 25]

# With a filter
evens = [x for x in range(20) if x % 2 == 0]
print(evens)

In [ ]:
# Exercise 1.5
# Use a list comprehension to collect all integers from 1 to 50
# that are divisible by 3 but NOT by 9.
# Print the result and its length.

# YOUR CODE HERE

## 2. NumPy

### 2.1 Why NumPy?

Python lists are flexible but slow for numerical work — each element is a full Python object with overhead. A NumPy **array** stores numbers in a contiguous block of memory, making it orders of magnitude faster for mathematical operations.

In [3]:
import numpy as np  # load the NumPy library and give it the short alias "np"
                    # "np" is a namespace: np.array(), np.zeros(), np.sin() etc. all live inside it
                    # writing "as np" is a universal convention — every NumPy resource uses it
import time

n = 1_000_000
py_list = list(range(n))
np_arr  = np.arange(n)

t0 = time.perf_counter()
result = [x**2 for x in py_list]
print(f"List loop: {time.perf_counter()-t0:.4f} s")

t0 = time.perf_counter()
result = np_arr**2
print(f"NumPy:     {time.perf_counter()-t0:.4f} s")

List loop: 0.0169 s
NumPy:     0.0064 s


### 2.2 Creating Arrays

In [ ]:
# Example 2.2
import numpy as np

a = np.array([1, 2, 3, 4, 5])        # from a list
b = np.zeros(5)                        # all zeros
c = np.ones((2, 3))                    # 2×3 matrix of ones
d = np.arange(0, 10, 2)               # 0, 2, 4, 6, 8  (step size 2)
e = np.linspace(0, 1, 5)              # 5 evenly-spaced values in [0, 1]

for arr in [a, b, c, d, e]:
    print(arr)

In [ ]:
# Exercise 2.2
# (a) Create a length-8 array of zeros, then set every other element
#     (indices 1, 3, 5, 7) to 1 using slice assignment.
# (b) Create 100 evenly-spaced values from 0 to 2π.  (Use np.pi.)
# (c) Create a 4×4 identity matrix.  Hint: np.eye.

# YOUR CODE HERE

### 2.3 Indexing and Slicing

For 2D arrays, use `[row, col]`. A `:` selects an entire axis.

In [ ]:
# Example 2.3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A[0, 1])       # single element: 2
print(A[:, 1])       # entire column 1: [2, 5, 8]
print(A[1, :])       # entire row 1:    [4, 5, 6]
print(A[0:2, 0:2])   # top-left 2×2 submatrix

In [ ]:
# Exercise 2.3
B = np.arange(25).reshape(5, 5)
print(B)
print()

# (a) Print the element at row 3, column 2.
# (b) Print the entire second column.
# (c) Print the 3×3 subarray in the bottom-right corner.

# YOUR CODE HERE

### 2.4 Arithmetic and Broadcasting

Operations between arrays happen **element-wise**. When shapes don't match, NumPy **broadcasts** the smaller array across the larger one — no explicit loops needed.

In [4]:
# Example 2.4
x = np.array([1.0, 2.0, 3.0, 4.0])

print(x * 2)       # scale
print(x + 10)      # shift
print(x ** 2)      # square element-wise
print(np.sqrt(x))  # square root element-wise

# Broadcasting: add a 1D array to each row of a 2D array
M = np.ones((3, 4))
v = np.array([0, 1, 2, 3])   # shape (4,) → broadcast over rows
print(M + v)

[2. 4. 6. 8.]
[11. 12. 13. 14.]
[ 1.  4.  9. 16.]
[1.         1.41421356 1.73205081 2.        ]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [ ]:
# Exercise 2.4
# (a) Let x = np.linspace(0, 2*np.pi, 300).
#     Compute y = sin(x) + 0.5*sin(2*x).
#     Print the maximum and minimum values of y.
#
# (b) Create a 3×3 matrix of ones and a vector v = [1, 2, 3].
#     Use broadcasting to multiply each ROW of the matrix by v.

# YOUR CODE HERE

### 2.5 Useful Array Functions

You will see two dot-notation patterns throughout this course:

**`array.method()`** — the dot calls a *method* that belongs to the array object itself.  
The array is the subject; it knows its own data.
```python
data.sum()    # sum of all elements in data
data.mean()   # mean of all elements in data
data.shape    # attribute (no parentheses) — returns the dimensions, e.g. (3, 3)
```

**`np.function(array)`** — the dot accesses a *function* from the NumPy namespace.  
The array is passed in as an argument.
```python
np.sort(data, axis=1)   # sort each row
np.sqrt(data)           # square root of every element
```

Both styles appear side-by-side in scientific code. The rule of thumb:  
methods like `.sum()` and `.mean()` are attached to the array; standalone tools like `np.sort()` live in the `np` namespace.

In [5]:
# Example 2.5
data = np.array([[3, 1, 4],
                 [1, 5, 9],
                 [2, 6, 5]])

print("shape:        ", data.shape)
print("total sum:    ", data.sum())
print("column sums:  ", data.sum(axis=0))
print("row sums:     ", data.sum(axis=1))
print("mean:         ", data.mean())
print("max:          ", data.max())
print("flat index of max:", data.argmax())
print("sorted rows:\n", np.sort(data, axis=1))

shape:         (3, 3)
total sum:     36
column sums:   [ 6 12 18]
row sums:      [ 8 15 13]
mean:          4.0
max:           9
flat index of max: 5
sorted rows:
 [[1 3 4]
 [1 5 9]
 [2 5 6]]


In [ ]:
# Exercise 2.5
rng = np.random.default_rng(seed=42)
M = rng.integers(0, 101, size=(6, 6))
print(M)
print()

# (a) Print the mean of each column.
# (b) Print the (row, col) index of the largest element.
#     Hint: np.unravel_index(np.argmax(M), M.shape)
# (c) Print a flattened, sorted version of the entire array.

# YOUR CODE HERE

## 3. Matplotlib

### 3.1 Line Plots

The standard import is `import matplotlib.pyplot as plt`. Always label your axes.

In [ ]:
# Example 3.1
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 300)
y = np.sin(x)

plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.title("Sine Wave")
plt.show()

In [ ]:
# Exercise 3.1
# On the same axes, plot y = cos(x) and y = cos(2x) over [0, 2π].
# Add axis labels, a title, and a legend.

# YOUR CODE HERE

### 3.2 Subplots

`plt.subplots(rows, cols)` returns a figure and an array of axes objects.

In [ ]:
# Example 3.2
x = np.linspace(0, 2 * np.pi, 300)

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

axes[0].plot(x, np.sin(x), color="steelblue")
axes[0].set_title("sin(x)")
axes[0].set_xlabel("x")

axes[1].plot(x, np.cos(x), color="darkorange")
axes[1].set_title("cos(x)")
axes[1].set_xlabel("x")

plt.tight_layout()
plt.show()

In [ ]:
# Exercise 3.2
# Create a 2×2 grid of subplots.
# In each panel, plot x^n for n = 1, 2, 3, 4 over x ∈ [0, 2].
# Give each panel an appropriate title.

# YOUR CODE HERE

### 3.3 Visualizing 2D Arrays

`imshow` maps a 2D array to a color grid — each entry becomes a pixel. This is useful throughout the course for visualizing matrices and operators.

In [ ]:
# Example 3.3
N = 60
x = np.linspace(-2, 2, N)
X, Y = np.meshgrid(x, x)
Z = np.exp(-(X**2 + Y**2))   # 2D Gaussian

plt.imshow(Z, origin="lower", extent=[-2, 2, -2, 2], cmap="viridis")
plt.colorbar(label="value")
plt.title("2D Gaussian")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

In [ ]:
# Exercise 3.3
# Visualize the 10×10 multiplication table as a heatmap.
# M[i, j] = (i+1)*(j+1) for i, j in 0..9.
# Add a colorbar and a title.

# YOUR CODE HERE